- defaults:
    link:
        create: true
        relink: true

- create:
    - ~/Downloads
    - ~/Documents/Pictures
    - ~/Documents/Videos
    - ~/.config/clangd/

- clean: [
    '~',
    '~/.config'
]
