CompileFlags:
    Add: [-Wall, -Wextra, -Wpedantic, -Wno-strict-prototypes, -O2, -ggdb3]
    Remove: [-W-strict-prototypes]

Diagnostics:
  ClangTidy:
    Add: [mpi-*, bugprone-*, readability-*, cert-env33-c,
          # cert-err33-c, # misc-unused-parameters,
          cert-err34-c, cert-flp30-c, misc-const-correctness,
          misc-definitions-in-headers, misc-misplaced-const,
          misc-non-copyable-objects, misc-redundant-expression,
          modernize-macro-to-enum]
    Remove: [readability-braces-around-statements,
             readability-identifier-length,
             readability-function-cognitive-complexity]

  UnusedIncludes: Strict

InlayHints:
  Enabled: Yes
  Designators: Yes
  ParameterNames: Yes
  DeducedTypes: Yes

---
# Fragment specific to C++ source files
If:
    PathExclude: [.*\.c, .*\.h]

CompileFlags:
    Add: [-std=c++20]

Diagnostics:
  ClangTidy:
    Add: [boost-use-to-string, bugprone-*, cert-*, clang-analyzer-*,
          concurrency-*, cppcoreguidelines-*, modernize-*, openmp-*,
          performance-*, portability-*, readability-*,
          fuchsia-multiple-inheritance]
    Remove: [cppcoreguidelines-owning-memory,
             readability-identifier-length,
             readability-function-cognitive-complexity]
